# Computation on NumPy Arrays: Universal Functions

## The Slowness of Loops



In [1]:
import numpy as np

values = np.random.randint(1, 100, size=1000000)

output = np.empty(len(values))

for i in range(len(values)):
    output[i] =  values[i] ** 2



In [2]:
output

array([1369.,   25., 1681., ..., 2304., 4225.,  961.])

In [3]:
values

array([37,  5, 41, ..., 48, 65, 31])

In [4]:
import timeit

In [5]:


values = np.random.randint(1, 100, size=1000000)

outputloop = np.empty(len(values))

outputufunc = np.empty(len(values))



In [6]:
%%timeit

for i in range(len(values)):
    outputloop[i] =  values[i] ** 2

259 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [7]:
#need to execute timeit doesnt execute

for i in range(len(values)):
    outputloop[i] =  values[i] ** 2

## Introducing UFuncs - Vectorized operations



In [8]:
%%timeit
outputufunc = values ** 2

300 µs ± 6.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
outputufunc = values ** 2

In [10]:
values.shape

(1000000,)

In [11]:
outputufunc.shape

(1000000,)

In [12]:
sum(outputufunc  - outputloop)

0.0

Vectorized operations in NumPy are implemented via *ufuncs*, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.
Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [13]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented using Python loops, especially as the arrays grow in size.
Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

### Array arithmetic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [14]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ``**`` operator for exponentiation, and a ``%`` operator for modulus:

In [15]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [16]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [35]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|



### Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions.
We'll start by defining an array of angles:

In [17]:
theta = np.linspace(0, np.pi, 3)

In [18]:
theta

array([0.        , 1.57079633, 3.14159265])

Now we can compute some trigonometric functions on these values:

In [19]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.
Inverse trigonometric functions are also available:

In [20]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [21]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [22]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [36]:
# Matmul or dot operates on Matrices. 

x = np.arange(1, 6)
x1 = x.reshape(5,1)

y = np.arange(6, 11)
y1 = y.reshape(1,5)



In [37]:
x1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
y1

array([[ 6,  7,  8,  9, 10]])

In [26]:
np.matmul(x1, y1)

array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20],
       [18, 21, 24, 27, 30],
       [24, 28, 32, 36, 40],
       [30, 35, 40, 45, 50]])

In [27]:
x = np.arange(1, 6)
x1 = x.reshape(5,1)

y = np.arange(6, 11)
y1 = y.reshape(1,5)



In [28]:
x1

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
y1

array([[ 6,  7,  8,  9, 10]])

In [30]:
np.dot(x1, y1)

array([[ 6,  7,  8,  9, 10],
       [12, 14, 16, 18, 20],
       [18, 21, 24, 27, 30],
       [24, 28, 32, 36, 40],
       [30, 35, 40, 45, 50]])

In [31]:
x = np.arange(1, 6)
y = np.arange(6, 11)



In [32]:
x

array([1, 2, 3, 4, 5])

In [33]:
y

array([ 6,  7,  8,  9, 10])

In [34]:
np.dot(x, y)

130

### Dot product of two 1D vector is scaler - element wise multiplication and summation of that -  as it is defined in mathematics. While dot product of two 2D Vectors - also called Matrices is matrix multiplication. 

####  This is the reason why we had to do a reshape above and perform dot product to get matrix multiplication. 

#### same is true for matmul function
