# Comparisons, Masks, and Boolean Logic

This section covers the use of Boolean masks to examine and manipulate values within NumPy arrays.
Masking comes up when you want to extract, modify, count, or otherwise manipulate values in an array based on some criterion: for example, you might wish to count all values greater than a certain value, or perhaps remove all outliers that are above some threshold.
In NumPy, Boolean masking is often the most efficient way to accomplish these types of tasks.

## Comparison Operators as ufuncs



In [11]:
x = np.array([1, 2, 3, 4, 5])

In [12]:
x < 3  # less than

array([ True,  True, False, False, False])

In [13]:
x > 3  # greater than

array([False, False, False,  True,  True])

In [14]:
x <= 3  # less than or equal

array([ True,  True,  True, False, False])

In [15]:
x >= 3  # greater than or equal

array([False, False,  True,  True,  True])

In [16]:
x != 3  # not equal

array([ True,  True, False,  True,  True])

In [17]:
x == 3  # equal

array([False, False,  True, False, False])

It is also possible to do an element-wise comparison of two arrays, and to include compound expressions:

In [18]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

As in the case of arithmetic operators, the comparison operators are implemented as ufuncs in NumPy; for example, when you write ``x < 3``, internally NumPy uses ``np.less(x, 3)``.
    A summary of the comparison operators and their equivalent ufunc is shown here:

| Operator	    | Equivalent ufunc    || Operator	   | Equivalent ufunc    |
|---------------|---------------------||---------------|---------------------|
|``==``         |``np.equal``         ||``!=``         |``np.not_equal``     |
|``<``          |``np.less``          ||``<=``         |``np.less_equal``    |
|``>``          |``np.greater``       ||``>=``         |``np.greater_equal`` |

Just as in the case of arithmetic ufuncs, these will work on arrays of any size and shape.
Here is a two-dimensional example:

In [4]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [5]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In each case, the result is a Boolean array, and NumPy provides a number of straightforward patterns for working with these Boolean results.

## Working with Boolean Arrays

Given a Boolean array, there are a host of useful operations you can do.
We'll work with ``x``, the two-dimensional array we created earlier.

In [18]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [19]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

### Counting entries

To count the number of ``True`` entries in a Boolean array, ``np.count_nonzero`` is useful:

In [20]:
# how many values less than 6?
np.count_nonzero(x < 6 )

8

In [21]:
np.sum(x < 6)

8

In [22]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

This counts the number of values less than 6 in each row of the matrix.

If we're interested in quickly checking whether any or all the values are true, we can use (you guessed it) ``np.any`` or ``np.all``:

In [23]:
# are there any values greater than 8?
np.any(x > 8)

True

In [24]:
# are there any values less than zero?
np.any(x < 0)

False

In [25]:
# are all values less than 10?
np.all(x < 10)

True

In [26]:
# are all values equal to 6?
np.all(x == 6)

False

``np.all`` and ``np.any`` can be used along particular axes as well. For example:

In [37]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [38]:
np.ma.count(x < 8, axis=0)

array([3, 3, 3, 3])

In [52]:
x_masked = x < 8

In [53]:
x_masked

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
# Counting True in masked Array - Remember features are always columns for 2 D array

np.count_nonzero(x_masked , axis = 0 )

array([3, 2, 3, 3])