# Introducing Pandas Objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices.
As we will see during the course of this chapter, Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

We will start our code sessions with the standard NumPy and Pandas imports:

In [110]:
import numpy as np
import pandas as pd

## The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [112]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [113]:
datanp = np.array([0.25, 0.5, 0.75, 1.0])
datanp

array([0.25, 0.5 , 0.75, 1.  ])

In [114]:
type(data)

pandas.core.series.Series

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.


In [115]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [67]:
type(data.values)

#got back a numpy 1D array

numpy.ndarray

In [71]:
data.index

RangeIndex(start=0, stop=4, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [72]:
data[1]

0.5

In [73]:
data[1:3]

1    0.50
2    0.75
dtype: float64

As we will see, though, the Pandas ``Series`` is much more general and flexible than the one-dimensional NumPy array that it emulates.

### ``Series`` as generalized NumPy array

``Series`` object is basically interchangeable with a one-dimensional NumPy array.


Difference-  Numpy Array has an *implicitly defined* integer index 

Pandas ``Series`` has an *explicitly defined* index associated with the values.



In [116]:
import pandas as pd

# Creating a Pandas Series with labels
data = {'Apple': 10, 'Banana': 5, 'Orange': 8, 'Grapes': 12}
fruits_series = pd.Series(data)

print(fruits_series)


Apple     10
Banana     5
Orange     8
Grapes    12
dtype: int64


In [75]:
fruits_series.values

array([10,  5,  8, 12])

In [76]:
fruits_series.index

Index(['Apple', 'Banana', 'Orange', 'Grapes'], dtype='object')

In [117]:
# And you access with index. Only that index in this case is not implicit integer.

In [118]:
fruits_series['Apple']

10

We can even use non-contiguous or non-sequential indices:

In [119]:
data = pd.Series([0.25, 0.25, 0.75, 1.0],
                 index=[4, 2, 2, 7])
data

4    0.25
2    0.25
2    0.75
7    1.00
dtype: float64

In [121]:
data[2]

# index need not be unique - but a good practice to ensure uniqueness 

2    0.25
2    0.75
dtype: float64

### Series as specialized dictionary



The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [122]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
#population


# For numpy array, we were using list to construct. For Pandas Series , we are using Dict . Why ?

In [84]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [85]:
#Like Dict
population['California']

38332521

In [86]:
#Slicing like Numpy
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

#### Looks like Pandas Series unlike Dict is an Ordered Collections

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [123]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

``data`` can be a scaler, which is repeated to fill the specified index:

In [26]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

``data`` can be a dictionary,

In [124]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In each case, the index can be explicitly set if a different result is preferred:

## The Pandas DataFrame Object

The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
We'll now take a look at each of these perspectives.

### DataFrame as a generalized NumPy array


In [131]:
area_dict = {'California': 423967, 'New York': 141297,'Texas': 695662, 
             'Florida': 170312, 'Illinois': 149995}

#area_dict = {'New York': 141297,'Texas': 695662, 
#             'Florida': 170312, 'Illinois': 149995}

            
            
area = pd.Series(area_dict)
area

California    423967
New York      141297
Texas         695662
Florida       170312
Illinois      149995
dtype: int64

In [133]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [132]:
states = pd.DataFrame({'population': population,
                       'area': area})
states
# So, Data Frame can be thought of as Set of aligned Pandas Series 

population    area
California    38332521  423967
Florida       19552860  170312
Illinois      12882135  149995
New York      19651127  141297
Texas         26448193  695662

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [135]:
states.index

Index(['California', 'Florida', 'Illinois', 'New York', 'Texas'], dtype='object')

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [136]:
states.columns

Index(['population', 'area'], dtype='object')

In [138]:
states.values

array([[38332521,   423967],
       [19552860,   170312],
       [12882135,   149995],
       [19651127,   141297],
       [26448193,   695662]])

In [139]:
states

population    area
California    38332521  423967
Florida       19552860  170312
Illinois      12882135  149995
New York      19651127  141297
Texas         26448193  695662

Thus the ``DataFrame`` can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

In [100]:
states['area']

California    423967
Florida       170312
Illinois      149995
New York      141297
Texas         695662
Name: area, dtype: int64

In [142]:
states['California']

KeyError: 'California'

In [101]:
states.loc['Texas']

#Notice how Numpy 2 D array and Pandas dataframe differs in how column and rows are retrieved.

population    26448193
area            695662
Name: Texas, dtype: int64

In [102]:
states.iloc[4]

# loc and iloc refers to indexing rows . When index are not numbers you can still refer with iloc.
#df['col name'] is for accessing dataframe columns

population    26448193
area            695662
Name: Texas, dtype: int64

In [105]:
states.iloc[4,0]

26448193

In [106]:
states.loc['Texas','population']

26448193

In [107]:
states['Texas']

KeyError: 'Texas'

In [108]:
states.loc['4','population']

KeyError: '4'

In [109]:
states.loc['Texas','1']

KeyError: '1'